version: 2.1

workflows:
  plan_approve_apply:
    jobs:
      - plan
      - hold-apply:
          type: approval
          requires:
            - plan-apply
      - apply:
          requires:
            - hold-apply
      - plan-destroy:
          requires:
            - apply
      - hold-destroy:
          type: approval
          requires:
            - plan-destroy
      - destroy:
          requires:
            - hold-destroy
      




jobs:
  plan:
    working_directory: /tmp/project
    docker:
      - image: terraform/default
    steps:
      - checkout
      - run:
          name: terraform init & Validate
          command: |
            terraform init
            terraform validate
      - run:
          name: terraform plan
          command: |
            terraform plan -out = ../../plan.out
      - persist_to_workspace:
          root: .
          paths:
            - ./credentials
            - ./env.txt
  apply:
    docker:
      - image: terraform/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform
          command: |
            terraform apply -auto-approve tfapply
      - persist_to_workspace:
          root: .
          paths:
            - .
  plan-destroy:
    docker:
      - image: terraform/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform create destroy plan
          command: |
            terraform plan -destroy -out tfdestroy -var-file terraform.tfvars
      - persist_to_workspace:
          root: .
          paths:
            - .

  destroy:
    docker:
      - image: terraform/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform destroy
          command: |
            terraform apply -auto-approve tfdestroy


