version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  plan-plan:
    working_directory: /tmp/project
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: terraform init & Validate
          command: |
            terraform init
            terraform validate
      - run:
          name: terraform plan
          command: |
            terraform plan -out = ../../plan.out
      - persist_to_workspace:
          root: .
          paths:
            - ./credentials
            - ./env.txt
      
